### ISSUE TITLE
pwait waits forever if PID does not exist

### ISSUE THREAD

**Issue by tbetker-rs** [leahneukirchen/extrace#4]
If a PID does not exist, `pwait` should return immediately. Instead, it waits forever because it never receives a netlink message that the PID has exited.

This can be fixed by checking the PIDs after connecting the netlink socket, but before running the netlink listener loop. I am attaching a (tested) patch that shows what I have in mind.

Note (1): I don't check for duplicate PIDs (as you do in the loop), so if a PID appears twice, you will see two messages "process id does not exist".

Note (2): I am not sure how to handle PID 0. You accept it as valid initially, but then use pids[n] = 0 to indicate that the PID has died. Since kill(0, ...) has a special meaning, I had to check for PID 0, and I have added a message telling the user that the PID is ignored, just in case.

Note (3): It might be helpful if `pwait` accepted an empty PID list, returning immediately without an error message. This would allow for things like `pwait $(pidof myprocess)`; that's just a suggestion, though.

[pwait-check-pids.patch.txt](https://github.com/chneukirchen/extrace/files/2388038/pwait-check-pids.patch.txt)

**Comment by leahneukirchen** [comment]
Fixed in b92fba5.

I adopted the FreeBSD behavior of ignoring invalid pids, and exiting if all pids are invalid.

**Comment by tbetker-rs** [comment]
Don't we still have a gap here if the PID goes away between kill() and PROC_CN_MCAST_LISTEN? I am not sure if this gap is in the FreeBSD code ... I would assume that

    EV_SET(e + nleft, pid, EVFILT_PROC, EV_ADD, NOTE_EXIT, 0, NULL);
    if (kevent(kq, e + nleft, 1, NULL, 0, NULL) == -1)
        ...

atomically checks that the PID exists and registers the event with the kernel event queue (so we can be certain to receive an event when the PID dies). I am not a FreeBSD expert, though, so that assumption may be completely wrong.

**Comment by tbetker-rs** [comment]
8e9bea214cac73a4fe033891a6e25338c12f3ecf looks good to me. Just a minor nit: If a SIGINT is received in the kill() loop, `sigint()` will set `quit = 1`, but the loop may overwrite that by `quit = 0` -- the signal is effectively ignored.

This can be avoided, e.g., by moving `signal(SIGINT, sigint);` behind the kill() loop, or by using a different flag variable in the loop.

**Comment by leahneukirchen** [comment]
Good point, moved it.

**Comment by tbetker-rs** [comment]
Oh my. I noticed too late that there is a similar `quit = 0;` overwrite at the end of the main loop. My fault. Perhaps use another flag variable in both places? Otherwise, I consider this closed as well.
